const toppingData = {
  Meats: [
    "Pepperoni",
    "Sausage",
    "Bacon",
    "Ground Beef",
    "Ham",
    "Chicken",
    "Salami",
    "Canadian Bacon",
    "Anchovies",
    "Prosciutto",
  ],
  Veggies: [
    "Mushrooms",
    "Green Peppers",
    "Onions",
    "Black Olives",
    "Green Olives",
    "Tomatoes",
    "Spinach",
    "Artichoke Hearts",
    "Red Onions",
    "Broccoli",
    "Jalapeños",
    "Banana Peppers",
    "Pineapple",
    "Sun-Dried Tomatoes",
    "Roasted Red Peppers",
    "Caramelized Onions",
    "Zucchini",
    "Asparagus",
    "Kalamata Olives",
    "Sliced Garlic",
    "Fresh Basil",
    "Avocado",
  ],
  Extras: [
    "Extra Cheese",
    "Feta Cheese",
    "Goat Cheese",
    "Blue Cheese",
    "Cheddar Cheese",
    "Parmesan Cheese",
    "Ricotta Cheese",
    "Sour Cream",
    "BBQ Sauce",
    "Buffalo Sauce",
    "Pesto Sauce",
    "Alfredo Sauce",
    "Olive Oil Drizzle",
    "Balsamic Glaze",
    "Sriracha Sauce",
    "Honey",
    "Crushed Red Pepper Flakes",
    "Fresh Oregano",
    "Truffle Oil",
    "Sliced Hard-Boiled Eggs",
  ],
};

export default toppingData